import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJS App</title>
        <meta name="description" content="Generated by @phemit/nexjs-boilerplate" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </div>
  )
}
